[2022-08-09 16:28:55,583] [views.py:43] [views:get_set] [ERROR]- OperationalError('no such column: account.account_status')
[2022-08-09 16:43:55,093] [views.py:94] [views:delete_account] [ERROR]- FieldError("Cannot resolve keyword 'account_id' into field. Choices are: robot_account_id, robot_create_time, robot_currency_type, robot_id, robot_policy_id, robot_policy_type, robot_status, robot_summary_id")
[2022-08-09 16:57:36,938] [views.py:162] [views:get_robot_info] [ERROR]- ProxyError(MaxRetryError("HTTPSConnectionPool(host='api.huobi.pro', port=443): Max retries exceeded with url: /v1/account/accounts/33269501/balance?account-id=33269501&AccessKeyId=5cd285c0-bewr5drtmh-a21ed20a-46286&SignatureVersion=2&SignatureMethod=HmacSHA256&Timestamp=2022-08-09T08%3A57%3A17&Signature=2fd07v0ijX8V1wFTsf0ev7w2DiYzB0mUWoyzhcoIlBE%3D (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))"))
[2022-08-09 17:21:11,434] [views.py:162] [views:get_robot_info] [ERROR]- ProxyError(MaxRetryError("HTTPSConnectionPool(host='api.huobi.pro', port=443): Max retries exceeded with url: /v1/account/accounts/33269501/balance?account-id=33269501&AccessKeyId=5cd285c0-bewr5drtmh-a21ed20a-46286&SignatureVersion=2&SignatureMethod=HmacSHA256&Timestamp=2022-08-09T09%3A20%3A52&Signature=usPcs1t%2FBD22TXtRxebvEjXQDno5WMyhYHJZmW2094A%3D (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))"))
[2022-08-09 17:25:49,804] [robot.py:180] [robot:cancel_order] [ERROR]- HuobiApiException('ExecuteError', '[Executing] order-orderstate-error: Incorrect order state')
[2022-08-09 17:25:49,964] [robot.py:180] [robot:cancel_order] [ERROR]- HuobiApiException('ExecuteError', '[Executing] order-orderstate-error: Incorrect order state')
[2022-08-09 17:25:50,128] [robot.py:180] [robot:cancel_order] [ERROR]- HuobiApiException('ExecuteError', '[Executing] order-orderstate-error: Incorrect order state')
[2022-08-09 17:25:50,299] [robot.py:180] [robot:cancel_order] [ERROR]- HuobiApiException('ExecuteError', '[Executing] order-orderstate-error: Incorrect order state')
[2022-08-09 17:25:50,484] [robot.py:180] [robot:cancel_order] [ERROR]- HuobiApiException('ExecuteError', '[Executing] order-orderstate-error: Incorrect order state')
[2022-08-09 17:25:50,487] [robot.py:190] [robot:cancel_orders] [ERROR]- Exception('撤销订单失败')
[2022-08-09 17:25:50,648] [robot.py:180] [robot:cancel_order] [ERROR]- HuobiApiException('ExecuteError', '[Executing] order-orderstate-error: Incorrect order state')
[2022-08-09 17:25:50,806] [robot.py:180] [robot:cancel_order] [ERROR]- HuobiApiException('ExecuteError', '[Executing] order-orderstate-error: Incorrect order state')
[2022-08-09 17:25:50,972] [robot.py:180] [robot:cancel_order] [ERROR]- HuobiApiException('ExecuteError', '[Executing] order-orderstate-error: Incorrect order state')
[2022-08-09 17:25:51,131] [robot.py:180] [robot:cancel_order] [ERROR]- HuobiApiException('ExecuteError', '[Executing] order-orderstate-error: Incorrect order state')
[2022-08-09 17:25:51,293] [robot.py:180] [robot:cancel_order] [ERROR]- HuobiApiException('ExecuteError', '[Executing] order-orderstate-error: Incorrect order state')
[2022-08-09 17:25:51,294] [robot.py:190] [robot:cancel_orders] [ERROR]- Exception('撤销订单失败')
[2022-08-09 17:25:51,457] [robot.py:180] [robot:cancel_order] [ERROR]- HuobiApiException('ExecuteError', '[Executing] order-orderstate-error: Incorrect order state')
[2022-08-09 17:25:51,623] [robot.py:180] [robot:cancel_order] [ERROR]- HuobiApiException('ExecuteError', '[Executing] order-orderstate-error: Incorrect order state')
[2022-08-09 17:25:51,782] [robot.py:180] [robot:cancel_order] [ERROR]- HuobiApiException('ExecuteError', '[Executing] order-orderstate-error: Incorrect order state')
[2022-08-09 17:25:51,943] [robot.py:180] [robot:cancel_order] [ERROR]- HuobiApiException('ExecuteError', '[Executing] order-orderstate-error: Incorrect order state')
[2022-08-09 17:25:52,113] [robot.py:180] [robot:cancel_order] [ERROR]- HuobiApiException('ExecuteError', '[Executing] order-orderstate-error: Incorrect order state')
[2022-08-09 17:25:52,113] [robot.py:190] [robot:cancel_orders] [ERROR]- Exception('撤销订单失败')
